# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=101

trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

variables:
- template: /eng/pipelines/templates/variables/sdk-defaults.yml
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: alpine319WithNode
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.19-WithNode
  - container: centosStream9
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9
  - container: debian11Amd64
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-amd64
  - container: fedora39
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-39
  - container: ubuntu2204
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04

stages:
############### BUILD STAGE ###############
- stage: build
  displayName: Build
  jobs:
  ############### WINDOWS ###############
  - template: /eng/pipelines/templates/jobs/sdk-job-matrix.yml@self
    parameters:
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals 1es-windows-2022-open
        os: windows
      helixTargetQueue: windows.amd64.vs2022.pre.open
