parameters:
  oneESCompat:
    templateFolderName: templates
  locBranch: ''
  ### WINDOWS ###
  windowsJobParameterSets:
  - categoryName: FullFramework
    testFullMSBuild: true

jobs:
### ONELOCBUILD ###
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.locBranch }}')) }}:
  - template: /eng/common/${{ parameters.oneESCompat.templateFolderName }}/job/onelocbuild.yml
    parameters:
      CreatePr: true
      LclSource: lclFilesfromPackage
      LclPackageId: LCL-JUNO-PROD-DOTNETSDK
      MirrorBranch: ${{ parameters.locBranch }}
      MirrorRepo: sdk
### BUILD JOBS ###
# Each job parameter set creates a new job and the parameter set is unwrapped into the parameters for that job.
# The parameters sent to this template are also passed to the job, which does include the os-specific jobParameterSets array, but that array itself isn't used in the job.
- ${{ if eq(parameters.pool.os, 'windows') }}:
  - ${{ each jobParameters in parameters.windowsJobParameterSets }}:
    - template: /eng/pipelines/templates/jobs/sdk-build.yml
      parameters:
        ${{ insert }}: ${{ parameters }}
        ${{ insert }}: ${{ jobParameters }}
- ${{ if eq(parameters.pool.os, 'linux') }}:
  - ${{ each jobParameters in parameters.linuxJobParameterSets }}:
    - template: /eng/pipelines/templates/jobs/sdk-build.yml
      parameters:
        ${{ insert }}: ${{ parameters }}
        ${{ insert }}: ${{ jobParameters }}
- ${{ if eq(parameters.pool.os, 'macOS') }}:
  - ${{ each jobParameters in parameters.macOSJobParameterSets }}:
    - template: /eng/pipelines/templates/jobs/sdk-build.yml
      parameters:
        ${{ insert }}: ${{ parameters }}
        ${{ insert }}: ${{ jobParameters }}
